package Verein;


/**
* Verein/VereinsMitglied.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from vmitglied.idl
* Sonntag, 19. Mai 2019 18:59 Uhr MESZ
*/

public interface VereinsMitglied extends VereinsMitgliedOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VereinsMitglied
